config/routes.rb
Calendar::Application.routes.draw do
  devise_for :users

  resources :user , :controller => 'user'
  match '/user', :to => 'user#create', :as => "create_user", :via => "put"
  match '/students/batches/:id', :controller => 'students', :action => 'batches', :format => 'js'
  match '/students/courses/:id', :controller => 'students', :action => 'courses', :format => 'js', :via => "get"

  resources :home, :only => :index
  resources :batches do
    get 'withdraw', :on => :member
  end
  resources :categories
  resources :courses do
    get 'enroll', :on => :member
    get 'assign', :on => :member
    get 'batches', :on => :member
    post 'student', :on => :member
  end
  resources :students do
    resources :comments
    get 'assign', :on => :member
  end
  resources :time_tables
  resources :tutors
  resources :days
  resources :slots
  resources :descriptions

  root :to =>"home#index"
  get "home/index"
end

app/models/student.rb
require 'active_support/secure_random'
class Student < ActiveRecord::Base
  before_create :assign_unique_identifier

  has_and_belongs_to_many :courses, :uniq => true
  has_and_belongs_to_many :batches, :uniq => true
  has_many :comments, :dependent => :destroy

  accepts_nested_attributes_for :comments, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
  validates_presence_of :first_name, :last_name, :email, :contact_number, :dob, :address, :payment_method
  validates_presence_of  :company_name,  :company_address, :company_contact_name, :company_contact_number, :if=>:type3?

  scope :with_status, lambda {|status| where("status = ?", status)}
  scope :current_unassigned, lambda { where("status IN ('CURRENT', 'UNASSIGNED')") }

  def assign_unique_identifier
    self.identifier = ActiveSupport::SecureRandom.urlsafe_base64(8)
  end

  def type3?
    self.student_type == 'Type_3'
  end

  def payment_methods options
      self.payment_method = options.join(",") unless options.nil?
  end

  def assign_batch batch
    self.batches ||=[]
    self.batches.push batch
    batch.update_attributes(:seats_available => batch.seats_available-1)
    self.status = 'CURRENT'
  end

  def assign_course course
    self.courses ||=[]
    self.courses.push course
  end

  def assign course, batch
    assign_batch batch
    assign_course course
    self
  end

  def withdraw_from batch
    self.batches.delete(batch)
    self.courses.delete(batch.course)
    update_status
    batch.seats_available +=1
    self.save!
  end

  def update_status
    self.status = self.batches.empty? ?  'UNASSIGNED' : 'CURRENT'
  end
end

app/models/student_type.rb
class StudentType < ActiveRecord::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  respond_to :html, :xml
  respond_to :js, :only => [ :courses, :batches]

  before_filter :authenticate_user!
  
  def index
    @students = Student.all
    flash[:notice] = "Currently there are no students. Please click on Add button to create one." if @students.empty?
    respond_with(@students)
  end

  def new
    @student = Student.new
    @student.comments.build
    respond_with(@student)
  end
  
   def show
    @student = Student.find(params[:id])
    respond_with(@student)
  end

  def create
    @student = Student.new(params[:student])
    @student.payment_methods(params[:payment_methods])
    if @student.save
      flash[:notice] = "Successfully created Student"
    end
    respond_with(@student, :location => students_path)
  end

  def edit
    @student = Student.find(params[:id])
    respond_with(@student)
  end

  def update
    params[:student][:course_ids] ||= []
    params[:student][:batch_ids] ||= []

    @student = Student.find(params[:id])
    @student.payment_methods(params[:payment_methods])
    
    old_batches = @student.batches.sort
    current_batches = Batch.where(:id => params[:student][:batch_ids]).to_a.sort

    if ((old_batches<=>current_batches)!=0)
      for batch in old_batches
        Batch.update(batch.id, "seats_available" => batch.seats_available + 1)
      end
      for batch in current_batches
        Batch.update(batch.id, "seats_available" => batch.seats_available - 1)
      end
    end

    if @student.update_attributes(params[:student])
      flash[:notice] = "Successfully updated Student"
    end
    respond_with(@student, :location => students_path)
  end

  def assign
    @student = Student.find(params[:id])
    @batchesAvailable = Batch.where(:course_id => @student.courses)
    respond_with(@batchesAvailable)
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to(students_path)
  end

  def batches
    @student = Student.new
    @batchesAvailable = Batch.where(:course_id => params[:id])
    respond_with(@batchesAvailable)
  end

  def courses
    @student = Student.new
    @coursesAvailable = Course.where(:category_id => params[:id])
    respond_with(@coursesAvailable)
  end
end

app/views/students/_comment_fields.html.erb
<div class="comment-fields">
    <%= f.text_field :commenter, :value => current_user.email , :hidden => true%>
    <%= f.label :content, "Comments" %><br/>
    <%= f.text_area :content, :rows => 3 %>
    <%= link_to_function "remove", "remove_fields(this)" %>
</div>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
    <%= render 'shared/errors', :target=>@student %>
    <%= render 'shared/student_fields', :f=>f %>
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

app/views/students/assign.html.erb
<%= form_for(@student) do |f| %>
    <div class="field">
        <% Batch.all.each do |batch| %>
            <%= check_box_tag "student[batch_ids][]", batch.id, @student.batches.include?(batch) %>
            <%= batch.code %>
        <% end %>
    </div>

    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

app/views/students/batches.js.erb
$('#batches-available').html('Batches<br/><% @batches.each do |batch| %><%= check_box_tag "student[batch_ids][]", batch.id, @student.batches.include?(batch) %><%= batch.code %>(Seats Available: <%=batch.seats_available%>)<br/><% end %>').html();

app/views/students/courses.js.erb
$('#courses-available').html('Courses<br/><% @courses.each do |course| %><%= check_box_tag "student[course_ids][]", course.id, @student.courses.include?(course) %><%= course.course_code %><br/><% end %>').html();

app/views/students/edit.html.erb
<h1>Editing Student</h1>
<%= form_for(@student) do |f| %>
    <%= render 'shared/errors', :target=>@student %>

    <div class="field">
        <%= f.label :first_name %><br/>
        <%= f.text_field :first_name %><br/>
    </div>
    <div class="field">
        <%= f.label :last_name %><br/>
        <%= f.text_field :last_name %><br/>
    </div>
    <div class="field">
        <%= f.label :email %><br/>
        <%= f.text_field :email %><br/>
    </div>
    <div class="field">
        <%= f.label :contact_number %><br/>
        <%= f.text_field :contact_number %><br/>
    </div>
    <div class="field">
        <%= f.label :dob %><br/>
        <%= f.text_field :dob, :class => "date-pick" %> <br/>
    </div>
    <br/>
    <div class="field">
        <%= f.label :address %><br/>
        <%= f.text_area :address, :rows=>3 %><br/>
    </div>
    <br/>
    <div class="field">
        <%= f.label :status %>
        <%= collection_select(:student, :status, StudentStatus.all, :code, :code)%><br/>
    </div>

    <div class="field">
        <%= f.label :student_type %>
        <%= collection_select(:student, :student_type, StudentType.all, :description, :description)%><br/>
    </div>

    <% if @student.student_type = 'Type_3' %>
        <div class="type3Details" style="display:block;">
             <%= f.label :company_name %>
             <%= f.text_field :company_name %><br/>
             <%= f.label :company_address %>
             <%= f.text_field :company_address %><br/>
             <%= f.label :company_contact_name %>
             <%= f.text_field :company_contact_name %><br/>
             <%= f.label :company_contact_number %>
             <%= f.text_field :company_contact_number %><br/>
        </div>
     <% end %>

    <div class="field" style="border: 1px solid; padding: 5px 5px 5px 5px;">
        <label>Enrollment Details</label> <br/><br/>
          <div class="field">
            <%= @student.payment_method.class %>
            <%= f.label :payment_method, "Payment Methods" %>
            <% PaymentMethod.all.each do |payment| %>
                <%= check_box_tag "student[payment_methods][]",payment.description%>
                <%= payment.description %>
                <!--<%= check_box_tag "payment_methods[]",payment.description%> <%= payment.description %>-->
             <% end %>
          </div>
            <div class="field">
             <%= f.check_box :fee_received %>
             <%= f.label :fee_received, "Fees Received" %><br/>
              <%= f.check_box :fee_processed %>
             <%= f.label :fee_received, "Fees Processed" %><br/>
             <%= f.check_box :docs_received %>
             <%= f.label :docs_received, "Documents Received" %><br/>
              <%= f.check_box :docs_processed %>
             <%= f.label :docs_received, "Documents Processed" %><br/>
          </div>
    </div>
    <%= f.text_field :enrolled_by, :value => current_user.email , :hidden => true%>
    <br/>
    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<div id='content'>
    <div id="content-body">
        <div id="description-bar">
            <div class="cell-data">Name</div>
            <div class="cell-data">DOB</div>
            <div class="cell-data">Adress</div>
            <div class="cell-data">Email</div>
            <div class="cell-data">Status</div>
            <div class="cell-data">Courses</div>
            <div class="cell-data">Batches</div>
            <div class="cell-data">Actions</div>
        </div>
        <% @students.each do |student| %>
            <div class="data-bar">
                <div class="cell-data">
                    <%= student.first_name %>
                </div>
                <div class="cell-data">
                    <%= student.dob %>
                </div>
                <div class="cell-data">
                    <%= student.address %>
                </div>
                <div class="cell-data">
                    <%= student.email %>
                </div>
                <div class="cell-data">
                    <%= student.status %>
                </div>
                <div class="cell-data">
                    <% student.courses.each do |course| %>
                        <%= course.course_code %><br/>
                    <% end %>
                </div>
                <div class="cell-data">
                    <% student.batches.each do |batch| %>
                        <%= batch.code %><br/>
                    <% end %>
                </div>
                <div class="action-cell">
                    <%= link_to "Add", assign_student_path(student)%> |
                    <%= link_to "Edit", edit_student_path(student)%> | 
                    <%= link_to "View", student%> |
                    <%= link_to "Delete", student, :confirm => 'Are you sure?', :method => :delete %>
                </div>
            </div>
        <% end %>
    </div>
    <div id="action-bar">
        <%= link_to 'Add New Student', new_student_path %>
    </div>
</div>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/random.html.erb
<div id="details-container">
        <div id="course-categories">
            <%=f.label :categories %><br/>
            <% Category.all.each do |category| %>
                <% if @categories!=nil %>
                    <%= check_box_tag "categories[]",category.id, @categories.include?(category)%>
                 <% else %>
                    <%= check_box_tag "categories[]",category.id%>
                 <% end %>
                <%= category.description %><br/>
            <% end %>
        </div>
        <div id="courses-available">
            <%=f.label :courses %><br/>
            <% @student.courses.each do |course| %>
                <%= check_box_tag "student[course_ids][]",course.id,  @student.courses.include?(course) %>
                <%= course.course_code %><br/>
            <% end %>
        </div>
        <div id="batches-available">
           <%=f.label :batches %><br/>
            <% @student.batches.each do |batch| %>
                <%= check_box_tag "student[batch_ids][]",batch.id,  @student.batches.include?(batch) %>
                <%= batch.code %>(Seats Available: <%=batch.seats_available%>)<br/>
            <% end %>
        </div>
    </div>
    <div class="comments-container">
         <% f.fields_for :comments do |builder| %>
            <%= render "comment_fields", :f => builder %>
        <% end %>
        <%= link_to_add_fields "Add Comments", f, :comments %>
    </div>

app/views/students/show.html.erb
<p class="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @student.name %>
</p>

<p>
  <b>DOB:</b>
  <%= @student.dob %>
</p>
<p>
  <b>Address:</b>
  <%= @student.address%>
</p>
<p>
  <b>Email:</b>
  <%= @student.email%>
</p>

<p>
  <b>Courses:</b>
  <% @student.courses.each do |course|%>
        <%= course.course_code %> <br/>
  <% end %>
</p>


<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>