config/routes.rb
Calendar::Application.routes.draw do
  devise_for :users

  resources :user , :controller => 'user'
  match '/user', :to => 'user#create', :as => "create_user", :via => "put"
  match '/students/batches/:id', :controller => 'students', :action => 'batches', :format => 'js'
  match '/students/courses/:id', :controller => 'students', :action => 'courses', :format => 'js', :via => "get"

  resources :home, :only => :index
  resources :batches do
    get 'withdraw', :on => :member
  end
  resources :categories
  resources :courses do
    get 'enroll', :on => :member
    get 'assign', :on => :member
    get 'batches', :on => :member
    post 'student', :on => :member
  end
  resources :students do
    resources :comments
    get 'assign', :on => :member
  end
  resources :time_tables
  resources :tutors
  resources :days
  resources :slots
  resources :descriptions

  root :to =>"home#index"
  get "home/index"
end

app/models/day.rb
class Day < ActiveRecord::Base
  has_many :slots
  belongs_to :time_table
  accepts_nested_attributes_for :slots, :reject_if => lambda { |a| a[:description].blank? }, :allow_destroy => true
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  respond_to :html, :xml
  before_filter :authenticate_user!

  def index
    @days = Day.all
    flash[:notice] = "Currently there are no days. Please click on Add button to create one." if @days.empty?
    respond_with(@days)
  end

  def show
    @day = Day.find(params[:id])
    respond_with(@day)
  end

  def new
    @day = Day.new
    @day.slots.build
    respond_with(@day)
  end

  def edit
    @day = Day.find(params[:id])
  end

  def create
    @day = Day.new(params[:day])
    if @day.save
      flash[:notice] = 'Day was successfully created'
    end
    respond_with(@day)
  end

  def update
    @day = Day.find(params[:id])
    if @day.update_attributes(params[:day])
      flash[:notice] = 'Day was successfully updated.'
    end
    respond_with(@day)
  end

  def destroy
    @day = Day.find(params[:id])
    @day.destroy
    redirect_to(days_path)
  end
end

app/views/days/_form.html.erb
<%= form_for(@day) do |f| %>
  <% if @day.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@day.errors.count, "error") %> prohibited this day from being saved:</h2>

      <ul>
      <% @day.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/days/edit.html.erb
<h1>Editing day</h1>

<%= render 'form' %>

<%= link_to 'Show', @day %> |
<%= link_to 'Back', days_path %>

app/views/days/index.html.erb
<div id='content-heading'>
    <h1>Listing Days</h1>
</div>
<p class="notice"><%= notice %></p>
<div id='content'>
    <div id="content-body">
        <div id="description-bar">
            <div class="cell-data">Day</div>
            <div class="cell-data"> Actions</div>
        </div>
        <% @days.each do |day| %>
            <div class="data-bar">
                <div class="cell-data">
                    <%= day.day %>
                </div>
                <div class="actions">
                    <div class="action-cell">
                        <p><%= log_pill_button_link_to 'Show', day %></p>

                        <p><%= edit_pill_button_link_to 'Edit', edit_day_path(day) %></p>

                        <p><%= negative_trash_pill_button_link_to 'Delete',day, :confirm => 'Are you sure?', :method => :delete %></p>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
    <div id="action-bar">
        <%= add_pill_button_link_to 'Add New', new_day_path %>
    </div>
</div>

app/views/days/new.html.erb
<h1>New day</h1>

<%= render 'form' %>

<%= link_to 'Back', days_path %>

app/views/days/show.html.erb
<div id="content-heading">
    <h1>Day Details</h1>
</div>

<p>
    <b>Day</b>
    <%= @day.day %>
</p>

<p>
    <b>Slots Available</b><br/>
    <%@day.Slots.each do |slot|%>
        <%= slot.description %><br/>
    <% end %>
</p>

<%= link_to 'Edit', edit_day_path(@day) %> |
<%= link_to 'Back', day_path %>